---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
--- 


## Loading and preprocessing the data
```{r, echo=FALSE}
  #Set up enviroment for R scrip  
  # Packages for tidyverse 
    library("tidyverse")
    library("lubridate")
  # Package for building tables in markdown and notebook 
    library("knitr")
    library("kableExtra") 
  # Package for forecasting
    library("fpp2")
  # Packages for reading excel and html files and XML
    library("openxlsx")
    library("XML")
  # Parkage for using data tables for very large data operations
    library("data.table")
  #Package for reading fixed width tables
    library("utils")
  # Packages for reading data through API's 
    library("httr")
    library("jsonlite")
  # Package for performing inquires with SQL databases 
    library("sqldf")
  #Package for reading and writing to jpeg files
    library("jpeg")

  # Set proper working Dir
    if (!getwd() == "C:/Users/paulr/Documents/R/Coursera_ReproducibleResearch/RepData_PeerAssessment1") {setwd("C:/Users/paulr/Documents/R/Coursera_ReproducibleResearch/RepData_PeerAssessment1")}
```


```{r}
  # Read data
    acticity <- read_csv("./data/activity.zip")
    tail(acticity)
    str(acticity)
    glimpse(acticity)
    summary(acticity)
    head(acticity)
    
```

## What is mean total number of steps taken per day?
I calcualte the total steaps taken each day.
```{r}
acticity %>% group_by(date) %>% summarise( TotalSteps = sum(steps), MeanSteps = mean(steps), MedianSteps = median(steps) ) -> acticity1

glimpse(acticity1)
view(acticity2)




ggplot(acticity1, aes(x = date, y = TotalSteps)) +
  geom_col()

acticity2 <- na.omit(acticity1)
median(acticity1$TotalSteps)
median(acticity2$TotalSteps)


```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
